### ISSUE TITLE
describe robustness for issue CF5

### ISSUE THREAD

**Issue by jokrah** [hpi-sam/robust-marl4sas#15]

**Comment by christianadriano** [comment]
CF5 correspond to a failure of servicing requests, because not enough instances of a component are available. However, one should not add more instances as necessary because that would add an overhead cost that would reduce the overall utility. Therefore, there is a concern that actions to fix CF5 (add or remove instances) might overshoot (too many instances) or undershoot (too few instances). The too few instances might be an issue when there are large and rapid fluctuations in the number of requests. In these cases, it might be challenging to determine how many instances on average are necessary to cope with the varying number of requests.

**Comment by christianadriano** [comment]
I just moved the text to Overleaf under the section Preliminaries.
